
server.port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: root
    password: academia
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

#ddl-auto
#validate: validate the schema, makes no changes to the database.
#update: update the schema.
#create: creates the schema, destroying previous data.
#create-drop: drop the schema at the end of the session
#none: is all other cases.